### ISSUE TITLE
Redesign the hero to include images

### ISSUE THREAD

**Issue by elliottwilliams** [matchboxcowork/matchboxstudio.org#11]
From @mikelberger:

> We discussed some changes to the website today.
> 
> Change the "hero" header to not be the video but to be an image. Randomly pick one out of several images (from the ones in the zip linked below) to show on load (not a carousel, a single image on each page load).
> 
> Have a "take the digital tour" button thing on that image that shows the Google Virtual tour in the place of the hero image. I'm not really sure how this should look. Give me some ideas/examples.
> 
> Move the current video down to the about section. Where the "See the Virtual Tour" thing is currently.
> 
> Let me know your thoughts and when you think you can get going on this (where it stands on your current task list).

A couple questions I have:
- Should the hero still be full-height, and take up the entire vertical space of the user's browser?
- Do you think it'd look better have the header at the bottom of the image (like it is now), or to move it on top of the image?
- I think it'd be best to provide some interface to switch between the photos. That way, if a user is looking for a particular photo (maybe they're in it, or maybe they saw it once and they're trying to show someone else), they can find it without knowing to reload the page over and over. Does that sound reasonable to you?

If I get a chance this week, I'll put together some wireframes of what I'm thinking.

@mikelberger & @amandafindlay, your thoughts?

**Comment by mikelberger** [comment]
Yes, still full height like the current video. I'd keep the header at the
bottom.

I don't think we need a way to switch photos. Let's keep this as simple as
we can. The photos shouldn't be informational. They're just background.

Thanks!

**Comment by elliottwilliams** [comment]
After today's meeting, we're going to pursue the design in #14 instead.
