### ISSUE TITLE
www does not responsd

### ISSUE THREAD

**Issue by mikelberger** [matchboxcowork/matchboxstudio.org#12]
The www subdomain for all domains does not respond.

http://www.matchboxlafayette.org
http://www.matchboxlafayette.com
http://www.matchboxstudio.org
http://www.matchboxcoworking.org
http://www.matchboxcoworking.com

There are DNS entries (A records pointing to 52.37.92.240) for each. I'm almost 100% at some point these worked.

Make this a top priority to fix.

**Comment by elliottwilliams** [comment]
While I'm working on this, should I make all of these domains redirect to http://matchboxstudio.org?

**Comment by mikelberger** [comment]
That would be fine if that's easiest.

**Comment by elliottwilliams** [comment]
Fixed. For reference, here is what the whole set of domains do, now that I've made changes to our `nginx.conf`:

```
http://matchboxstudio.org          -> 200
http://matchboxcoworking.com       -> 301 http://matchboxstudio.org/
http://matchboxcoworking.org       -> 301 http://matchboxstudio.org/
http://matchboxlafayette.com       -> 301 http://matchboxstudio.org/
http://matchboxlafayette.org       -> 301 http://matchboxstudio.org/
http://www.matchboxcoworking.com   -> 301 http://matchboxstudio.org/
http://www.matchboxcoworking.org   -> 301 http://matchboxstudio.org/
http://www.matchboxlafayette.com   -> 301 http://matchboxstudio.org/
http://www.matchboxlafayette.org   -> 301 http://matchboxstudio.org/
http://www.matchboxstudio.org      -> 301 http://matchboxstudio.org/
```
