### ISSUE TITLE
Google Maps embeds should not respond to scroll events.

### ISSUE THREAD

**Issue by elliottwilliams** [matchboxcowork/matchboxstudio.org#20]
We have a couple full-width Maps embeds (the map view and the virtual tour). Right now, unless you're fast it's impossible to scroll past them, because the Maps widgets steal scroll events and respond to them by zooming in/out of the map. We should disable this interaction and rely on the zoom controls within the widget, to make it easier to scroll around the page.

I think this can be done in the configuration for the Maps widgets, but if not, we could probably write some JS that intercepts `scroll` events and makes sure they are forwarded up the DOM.

**Comment by mikelberger** [comment]
Will not fix this. Too much time for the value it gives. Every site with a map embedded has this issue.
