### ISSUE TITLE
Entrepreneur paper 404s

### ISSUE THREAD

**Issue by mikelberger** [matchboxcowork/matchboxstudio.org#26]
This page is a 404.

http://matchboxstudio.org/entrepreneur

**Comment by elliottwilliams** [comment]
My bad — I deleted it in https://github.com/matchboxcowork/matchboxstudio.org/commit/1c991cdf430338858ac2248d965d9bc3bafe589f as I noticed it wasn't linked to anywhere else. If we still need it, I can add it back.

**Comment by mikelberger** [comment]
Yes, please add it back. We don't link to it from the main page but we
direct link to it in emails and some other places where we need it.

Please let me know when it is back up. Thanks.

**Comment by elliottwilliams** [comment]
It's back up. Sorry again!

For reference, here are all the publicly-accessible non-admin pages at matchboxstudio.org right now. If you see anything missing, let me know:

matchboxstudio.org/index.html
matchboxstudio.org/entrepreneur/index.html
matchboxstudio.org/thanks.php

**Comment by mikelberger** [comment]
Thanks!
