### ISSUE TITLE
Redesign sponsors

### ISSUE THREAD

**Issue by elliottwilliams** [matchboxcowork/matchboxstudio.org#4]
We've talked about this offline, but the plan is to redesign the sponsors widget so that it shows more sponsors at once than before.

At the same time, we need to verify that current sponsors are all there. As far as I know, I need to remove Cook.

**Comment by elliottwilliams** [comment]
Toyed around with this for a little while, this is what it looked like when I stopped work on 14 June:

![screen shot 2016-06-14 at 23 05 14](https://cloud.githubusercontent.com/assets/910198/16066818/8c000f02-3284-11e6-8f54-74423b4558e3.png)

**Comment by mikelberger** [comment]
I think this looks good as it is. My only questions/concerns relate to how it looks on mobile and how do we add/remove sponsors and not have to redesign the whole layout. The entire site isn't as awesome as it could be on mobile. Making it better or at least not making it worse would be a goal. Is that one giant image with all of the logos? If we add a new sponsor, how do we update this? Make a new a whole new image or add the new sponsor logo to the server and update the HTML/Haml?

**Comment by elliottwilliams** [comment]
Yeah. The images are layed out with flexbox, so they will re-flow onto mobile, but right now I think they end up too big:

![screen shot 2016-06-15 at 08 53 46](https://cloud.githubusercontent.com/assets/910198/16080407/b1ce1c0e-32d6-11e6-9284-de8eba594cbf.png)

I think if I just render them a little smaller on mobile screens it'll look fine.

Adding a new sponsor now requires just updating the file [`sponsors.yaml`](https://github.com/matchboxcowork/matchboxstudio.org/blob/4_sponsors/partials/sponsors.yaml).

**Comment by mikelberger** [comment]
Sounds good. If you are resizing images anyway, try to get them to be a
little more balanced/even in size. I tried some but it is hard because they
are at such different aspect ratios and level of details. The goal is to
give sponsors all sort of equal billing on the site (we have other ways
where bigger sponsors get more visibility)
